### PR TITLE
Refactoring: Split main.rs into lib.rs

### PR DESCRIPTION
**Pull request by frederictobiasc**
Hi,
this PR
1. moves code from `main.rs` into the newly created `lib.rs`.
2. Updates the dependencies
3. Applies ~alejandra~ `nixfmt` formatter for the nix files

I used the recommendations from [the book](https://doc.rust-lang.org/book/ch12-03-improving-error-handling-and-modularity.html#separation-of-concerns-for-binary-projects) as guiding principles. I hope you find this helpful.

### CODE REVIEW

**Comment by astro** [comment]
Cool! Could you take care of the few Clippy warnings?

I am not too fond of alejandra's defaults but consistency is king...

**Comment by frederictobiasc** [comment]
Yes, sure. When I made the PR, I did not check your actions config and checked clippy without pedantic ;)

If you prefer a different nix formatter, I'm happy to switch.

**Comment by astro** [comment]
> Yes, sure. When I made the PR, I did not check your actions config and checked clippy without pedantic ;)

That's what CI is for!

> If you prefer a different nix formatter, I'm happy to switch.

I have a slight preference for nixfmt if you don't mind.

**Comment by astro** [comment]
Thank you very much!

**Pull request merged**
