### PR TITLE
Add option to set configFile directly

### PR DESCRIPTION
**Pull request by SuperSandro2000**
So that it can be put into sops-nix

Tested on my deployment.

### CODE REVIEW

**Comment by astro** [comment]
The `config` option seems now unused and should be removed?

I am not sure I want all non-secret config in sops instead of in nix...

**Comment by SuperSandro2000** [comment]
Maybe the config loader could be changed to allow loading multiple files? then the secrets could be extracted into a separate file or more easily allow loading them via env variables.

> I am not sure I want all non-secret config in sops instead of in nix...

Yeah, that is not that nice. Would be could if it would be a freeform setting, too.

**Comment by frederictobiasc** [comment]
@astro 
> The `config` option seems now unused and should be removed?

It's still used as default ([see here](https://github.com/astro/ifdyndnsd/pull/11/files#diff-9ae72e042240ea8af44b0b7d64302d780bf8658d51915a00bc0b70b4aa8b556eR14)) so existing setups will continue to work.

@SuperSandro2000 
> more easily allow loading them via env variables.

So for instance read the secret from an env var that is derived by the key name?

> Maybe the config loader could be changed to allow loading multiple files? then the secrets could be extracted into a separate file

Do you have a concrete implementation for something like this in mind? I cannot relate to that.

Are you aware of the `secret-file-base64` configuration option? That's what I'm using together with `sops-nix`.

**Review by frederictobiasc — APPROVED** [review]
LGTM

**Comment by SuperSandro2000** [comment]
> So for instance read the secret from an env var that is derived by the key name?

yes



> Do you have a concrete implementation for something like this in mind? I cannot relate to that.

matrix synapse allows that via the --config-path argument https://github.com/matrix-org/synapse/blob/93f2fdd8d1d56a55bddc5b13fd46042ecabea178/docker/README.md?plain=1#L126-L127



> Are you aware of the `secret-file-base64` configuration option? That's what I'm using together with `sops-nix`.

That should also work. 🤔

**Pull request merged**
